### ISSUE TITLE
uniapp 移动端持久化失败

### ISSUE THREAD

**Issue by wangqiJava** [Allen-1998/pinia-plugin-persist-uni#10]
uniapp 移动端持久化失败

**Comment by wangqiJava** [comment]
我自己改了一下源码可以了😁

**Comment by Allen-1998** [comment]
如何修复的呢，是和 `isH5` 这个判断有关吗 https://github.com/Allen-1998/pinia-plugin-persist-uni/issues/3#issuecomment-1192176830 ，因为本人没有用 uni 开发 app 的经验，所以对于如何区分 app 环境没有一个很好的方式，如果可以提出任何建议将不胜感激

**Comment by wangqiJava** [comment]
app端会走isH5的分支但是有问题，我是加了个判断app端的判断，app端得用uni自带的方法存储，但是我现在还是没解决🤣，有的能存进去有的存不进去

**Comment by wangqiJava** [comment]
// #ifdef APP-PLUS
isH5 = false
// #endif
我就加了个这个判断，但是还是不行，希望大佬能把app端也兼容进去😁

**Comment by Allen-1998** [comment]
> app端会走isH5的但是分支有问题，我是加了个判断app端的判断，app端得用uni自带的方法存储，但是我现在还是没解决🤣，有的能力存在进去，有的存在不进去

有的能存进去有的存不进去指的是，存不进去的案例和正常的有什么区别嘛，理论上来说如果可以存储的话都没问题才对

**Comment by wangqiJava** [comment]
我现在本地测试app端，加载完pinia的store配置，export default ({ options, store }: PiniaPluginContext): void => {这段打印options是空的，web端是有的

**Comment by wangqiJava** [comment]
相关的pinia设置写法是按照你写的哪个插件用例里面的写法

**Comment by Allen-1998** [comment]
> // #ifdef APP-PLUS isH5 = false // #endif 我就加了个这个判断，但是还是不行，希望大佬能把app端也兼容进去😁

想过用这种方式，没有使用的原因是：
1. esbuild 在打包时会删除注释，并且我查阅了 esbuild 的 issues，官方明确说明了不会提供不删除注释的选项
2. 或者可以选择不使用esbuild压缩代码，但是感觉作为一个lib来说不压缩还是不够合理，并且在包里写这种 `魔法注释` 总感觉不够优雅

**Comment by Allen-1998** [comment]
> 我现在本地测试app端，加载完pinia的store配置，export default ({ options, store }: PiniaPluginContext): void => {这段打印options是空的，web端是有的

我创建有一个 [uni 的项目模版](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia) ，插件在这个项目的 app环境是运行正常的，可以把它 clone 下来对比和你的项目有什么区别，或者提供一个最小复现我帮你看一下也可以

**Comment by wangqiJava** [comment]
我用的就是这个模板🤣，我只是想解决目前这个问题，不知道为什么不生效

**Comment by Allen-1998** [comment]
> 我用的就是这个模板🤣，我只是想解决目前这个问题，不知道为什么不生效

按模版直接 `npm run build:app-android` 打包运行，在我这边是正常的，环境
- node v16.20.0
- hbuildx 3.7.11
- android 13

不确定是依赖/环境原因，还是加入了其他的业务逻辑导致的，需要提供详细的信息

**Comment by wangqiJava** [comment]
我是hbuilder真机调试状态下

- hbuildx 3.8.4

打包也是用hbuilder云打包的

**Comment by Allen-1998** [comment]
🤔更新了我的 hbuildx 到 3.8.4，但是真机调试和云打包持久化存储的效果依然都是正常的

**Comment by wangqiJava** [comment]
🫣为什么我不行，有什么特殊配置吗，我现在只能手动持久化了。。。

**Comment by Allen-1998** [comment]
那个模版项目拉下来之后直接打包，测试页那个 updateName 的demo,持久化效果就是正常的，任何其他配置都没做

**Comment by wangqiJava** [comment]
找到原因了，是因为初始时我在路由守卫里面使用了useStore去设置state值，可能这个时候pinia和插件没有加载好（猜测），所以登录后action执行一系列方法设置satae值，这时候路由守卫里面useStore就可以了，谢谢大佬
