### ISSUE TITLE
uniapp 打包到快手小程序出现报错

### ISSUE THREAD

**Issue by alun-430** [Allen-1998/pinia-plugin-persist-uni#12]
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/29272929/4bcc12c8-968c-4b61-8331-35a3aaddcd79)
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/29272929/8a01864e-6f7b-4363-bf17-302c32cdf78b)
这里的判断条件需要修改一下

**Comment by Allen-1998** [comment]
https://github.com/Allen-1998/pinia-plugin-persist-uni/blob/fc85b1fa063643980e853bca11cdcd9cad8fd76c/src/index.ts#L69C9-L69C9
对应的是这里的哪个判断呢，本人没有开发快手小程序的经验，可以交流一下

**Comment by alun-430** [comment]
<img width="623" alt="image" src="https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/29272929/3798a347-0743-4838-87cd-8db289931d78">

**Comment by Allen-1998** [comment]
如果是小程序的话，不应该走进这个 if 里，所以想看一下是判断条件中的哪个有问题，是 `isH5` 返回 `true` 了嘛

**Comment by Allen-1998** [comment]
快手小程序应该执行进 else 里的 `uni.getStorageSync` 才对

**Comment by alun-430** [comment]
isH5 是  false

**Comment by alun-430** [comment]
走到了后面的判断条件

**Comment by Allen-1998** [comment]
`store` 中的 `persist ` 是如何设置的呢，应该是只有设置了 `persist.enforceCustomStorage: true` 才会走进来的

**Comment by alun-430** [comment]
所有用到的地方 store 中都是这样设置的：
persist: {
    enabled: true
  }

**Comment by Allen-1998** [comment]
可以帮忙打印一下 `options` 的输出嘛，代码逻辑看起来是没问题的

**Comment by sunpm** [comment]
<img width="463" alt="image" src="https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/35005831/545a1f1b-01c6-49ce-9951-cbd8879bf313">

问题出在 isH5 的判断上面，如果这个插件是专给 uniapp 使用的，可否使用条件编译？

**Comment by Allen-1998** [comment]
> 问题出在 isH5 的判断上面，如果这个插件是专给 uniapp 使用的，是否可以否决使用条件编译？

感谢分享，之前有考虑过这种实现方式 https://github.com/Allen-1998/pinia-plugin-persist-uni/issues/3#issuecomment-1191372863 ，可以再讨论一下

**Comment by Allen-1998** [comment]
fixed in  https://github.com/Allen-1998/pinia-plugin-persist-uni/pull/13
