### ISSUE TITLE
持久化配置无效？

### ISSUE THREAD

**Issue by xkfe** [Allen-1998/pinia-plugin-persist-uni#15]
自己项目配置了查看无效，也下载了 [uni-vue3-vite-ts-pinia](https://github.com/ttk-cli/uni-vue3-vite-ts-pinia) 项目到本地查看也没看到本地缓存数据，是用法不对吗？
<img width="1208" alt="Snipaste_2024-01-21_15-16-24" src="https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/129662190/7d11f695-f1ea-43fe-a2e0-d471c44bbbb4">

**Comment by Allen-1998** [comment]
1. 确认下使用的是 localStorage 还是 sessionStorage
2. 数据写入缓存的时机在被set,也就是更新了后，所以项目第一次启动，所有的值都是默认值的时候缓存中是没有内容的

**Comment by xkfe** [comment]
可以了，感谢感谢🙏。忘记需要修改缓存值了

**Comment by xkfe** [comment]
@Allen-1998 可以再请教您一个问题吗？就是有个 ts 类型错误是什么原因呀？
![Snipaste_2024-01-22_16-49-03](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/129662190/4a5752d0-e13f-46c2-bc56-5e30c4d3b11a)

**Comment by Allen-1998** [comment]
在示例项目中有报错吗，如果没有的话，可能是依赖版本相关的兼容性问题，建议新开一个issues,并提供最小复现
