### ISSUE TITLE
小程序存储异常

### ISSUE THREAD

**Issue by CodeXiaoYan** [Allen-1998/pinia-plugin-persist-uni#16]

**Comment by CodeXiaoYan** [comment]
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/88218823/bb53ca48-06d0-4427-b31b-65ff444d212f)

**Comment by CodeXiaoYan** [comment]
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/88218823/3ca65967-f555-470b-94ac-a30fafb8c72d)
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/88218823/bc12e59c-ebf1-4710-a9da-03ca1b115292)
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/88218823/1e59ecf1-c187-4ca4-b4b3-db3aba329dfd)
![image](https://github.com/Allen-1998/pinia-plugin-persist-uni/assets/88218823/97353629-dc33-447f-ba4a-0c98743fef38)

**Comment by CodeXiaoYan** [comment]
界面拿到了userinfo ，没有存储到缓存

**Comment by Allen-1998** [comment]
> ![image](https://private-user-images.githubusercontent.com/88218823/324663514-bb53ca48-06d0-4427-b31b-65ff444d212f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzM3MTUsIm5iZiI6MTcxMzg3MzQxNSwicGF0aCI6Ii84ODIxODgyMy8zMjQ2NjM1MTQtYmI1M2NhNDgtMDZkMC00NDI3LWIzMWItNjVmZjQ0NGQyMTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4M2NkZmI0OGQ1MGYzZTQ5YzFkYzg1N2ZhMzA4YjIyODZhNzY5ZTA0ZjU2YmVkM2NjN2QyZTA5YTFiM2YyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i2OyuGjGTLuivixdioH5W1yQ7zSmNEgdBJRia7J1xk8)

storage 被设置为了 window.localStorage, 这在小程序中是不存在的

**Comment by Allen-1998** [comment]
不清楚你这么设置的应用场景是什么，一个 uniapp 中开发 h5 和小程序， 然后希望 h5 那边的持久化使用 localStorage 吗
如果是这个场景的话，只需要设置 H5Storage: window?.localStorage 就可以了，strategies 的 item 中不用设置 storage，内部处理逻辑见 https://github.com/Allen-1998/pinia-plugin-persist-uni/blob/main/src/index.ts#L69

**Comment by CodeXiaoYan** [comment]
11
