### ISSUE TITLE
微信小程序提示解析错误，实际上有数据

### ISSUE THREAD

**Issue by baseSky** [Allen-1998/pinia-plugin-persist-uni#4]
https://github.com/Allen-1998/pinia-plugin-persist-uni/blob/ffcb7b8ebc9f32fdbd86cda9c8db283f53639fb9/src/index.ts#L73

**Comment by Allen-1998** [comment]
@baseSky 可以提供最小复现吗

**Comment by baseSky** [comment]
直接用就行。开启了 ` enabled: true `

**Comment by baseSky** [comment]
`
import { useAppStore } from '@/stores/app' 
const store = useAppStore()
store.getConfig();
`

**Comment by baseSky** [comment]
```
import {
	defineStore
} from 'pinia'
export const useAppStore = defineStore('app', {
	id: 'app',
	state: () => {
		return {
		}
	},
	actions: {
		async getConfig() {

		}
	},
	persist: {
		enabled: false,
		H5Storage: window?.localStorage,
	},
})
```

**Comment by baseSky** [comment]
第一次是可以的，刷新一下就不行了

**Comment by Allen-1998** [comment]
在我的项目中是正常的，有可能是pinia或者其他依赖的版本不正确，可以建一个仓库创建一个最小复现吗

**Comment by baseSky** [comment]
ok,是我把缓存名称用成一个了。
