### ISSUE TITLE
在安卓真机运行，没有办法持久化存储

### ISSUE THREAD

**Issue by wenqiangY** [Allen-1998/pinia-plugin-persist-uni#5]

**Comment by Allen-1998** [comment]
使用的 `pinia-plugin-persist-uni` 是最新版 1.1.5 吗，是否可以创建一个最小复现，在我的项目中是正常的

**Comment by wenqiangY** [comment]
您好，非常感觉您百忙之中能回复我的问题。我运行了新的dome发现并没有问题，之后通过排查项目代码，发现是因为我在setup外面引入的代码导致缓存失效，猜测可能是组件重新生成了userStore把页面中的userStore覆盖了。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Allen-1998/pinia-plugin-persist-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Allen-1998/pinia-plugin-persist-uni] 在安卓真机运行，没有办法持久化存储 (Issue #5)





 
使用的 pinia-plugin-persist-uni 是最新版 1.1.5 吗，是否可以创建一个最小复现，在我的项目中是正常的

**Comment by Allen-1998** [comment]
好的，没问题的话这个issue就关闭了
