### ISSUE TITLE
更新了store 数据没变

### ISSUE THREAD

**Issue by haobarry** [Allen-1998/pinia-plugin-persist-uni#7]
我在小程序使用时 ,发现修改了pinia定义的state, state确实里面确实改变了,但是小程序数据缓存里的并没有改变

**Comment by Allen-1998** [comment]
可以提供一下对应代码片段或最小复现吗

**Comment by haobarry** [comment]
> 

不好意思,我设定的字符太长,是我看错了.. 

另外有个问题,这个插件在初始化的时候,并不能直接创建到缓存是么?  必须要修改一次这个store,中的state,才能创建?

**Comment by Allen-1998** [comment]
是的，因为插件本身是基于 pinia 的 $subscribe 来实现的，它的作用就是在存储变化的时候执行一些操作，另外设想一下，在初始化的时候直接创建到缓存的话，无疑会在用户首次加载的时候增加很多不必要的开销，这是不合适的

**Comment by haobarry** [comment]
> 是的，因为插件本身是基于 pinia 的 $subscribe 来实现的，它的作用就是在存储变化的时候执行一些操作，另外设想一下，在初始化的时候直接创建到缓存的话，无疑会在用户首次加载的时候增加很多不必要的开销，这是不合适的

明白  谢谢了
