### ISSUE TITLE
关于H5平台默认存储方式

### ISSUE THREAD

**Issue by 546200350** [Allen-1998/pinia-plugin-persist-uni#8]
uni针对H5官方有说明是存储到localstorage。
建议将默认配置改成localstorage

**Comment by Allen-1998** [comment]
1. 市面上所有h5持久化插件的默认存储都为sessionStorage 
2. 插件支持了修改h5存储的配置项，可以根据不同的应用场景进行灵活配置
3. 如果修改默认为localStorage会对已经在使用的朋友造成破坏性更新

感谢你的建议，但是基于以上几点，不会对插件中现有的默认配置进行修改
