### ISSUE TITLE
paths怎么配置

### ISSUE THREAD

**Issue by mrbin1573** [Allen-1998/pinia-plugin-persist-uni#9]
paths怎么配置

**Comment by Allen-1998** [comment]
可以参考 https://allen-1998.github.io/pinia-plugin-persist-uni/advanced/custom-storage.html 示例中 paths 的用法，当你只希望存储部分数据时，可以用它来指定，相关代码逻辑见 https://github.com/Allen-1998/pinia-plugin-persist-uni/blob/main/src/index.ts#L35-L45
